export const weatherIcons = [
  {
    id: 200,
    main: 'Thunderstorm',
    description: 'thunderstorm with light rain',
    icon: '11d',
    svg: 'WiThunderstorm',
  },
  {
    id: 300,
    main: 'Drizzle',
    description: 'light intensity drizzle',
    icon: '09d',
    svg: 'WiRain',
  },
  {
    id: 301,
    main: 'Drizzle',
    description: 'drizzle',
    icon: '09n',
    svg: 'WiRain',
  },
  {
    id: 500,
    main: 'Rain',
    description: 'light rain',
    icon: '10n',
    svg: 'WiRain',
  },
  {
    id: 501,
    main: 'Rain',
    description: 'proximity moderate rain',
    icon: '10d',
    svg: 'WiRain',
  },
  {
    id: 511,
    main: 'Rain',
    description: 'freezing rain',
    icon: '13n',
    svg: 'WiRain',
  },
  {
    id: 701,
    main: 'Mist',
    description: 'mist',
    icon: '50d',
    svg: 'WiDust',
  },
  {
    id: 741,
    main: 'Fog',
    description: 'fog',
    icon: '50n',
    svg: 'WiFog',
  },
  {
    id: 800,
    main: 'Clear',
    description: 'Sky is Clear',
    icon: '01d',
    svg: 'WiDaySunny',
  },
  {
    id: 801,
    main: 'Clouds',
    description: 'few clouds',
    icon: '02d',
    svg: 'WiDayCloudy',
  },
  {
    id: 802,
    main: 'Clouds',
    description: 'scattered clouds',
    icon: '03d',
    svg: 'WiCloudy',
  },
  {
    id: 803,
    main: 'Clouds',
    description: 'broken clouds',
    icon: '04d',
    svg: 'WiCloudy',
  },
];
